language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
before_install:
  - perlbrew install-cpanm -f
install:
  - cpanm -n --installdeps --with-develop .
script:
  - perl -Mlib::core::only -c access_log.pl
sudo: false
